/** Per-check remediation one-liner + optional guide for the /checks catalog. */
export const CHECK_GUIDE: Record<string, { fix: string; guide?: string }> = {
  "T22-001": { fix: "Assert transferring state at the top of every hook handler.", guide: "transfer-hook-checklist" },
  "T22-002": { fix: "Remove same-mint CPI transfers from inside the hook.", guide: "transfer-hook-checklist" },
  "T22-003": { fix: "Build ExtraAccountMetaList from Seed:: and re-derive PDAs in the hook.", guide: "transfer-hook-checklist" },
  "T22-004": { fix: "Use anchor_spl::token_interface instead of anchor_spl::token.", guide: "token2022-not-spl" },
  "T22-005": { fix: "Replace transfer() with transfer_checked (or transfer_checked_with_fee).", guide: "transfer-fees" },
  "T22-006": { fix: "Use transfer_checked_with_fee; do not mix calculate_fee and calculate_inverse_fee.", guide: "transfer-fees" },
  "T22-007": { fix: "Inspect PermanentDelegate on incoming mints before accepting deposits.", guide: "vault-extensions" },
  "T22-008": { fix: "Treat confidential balances as opaque; audit non-zero auditor keys.", guide: "token2022-not-spl" },
  "T22-009": { fix: "Compute size with ExtensionType::try_calculate_account_len.", guide: "token2022-not-spl" },
  "T22-010": { fix: "Enable CpiGuard on program-owned vault token accounts.", guide: "vault-extensions" },
  "T22-011": { fix: "Set ImmutableOwner on custodied token accounts at creation.", guide: "vault-extensions" },
  "T22-012": { fix: "Add Anchor fallback dispatcher for Execute discriminator.", guide: "transfer-hook-checklist" },
  "T22-013": { fix: "Attach SPL Memo before transfers to memo-required accounts.", guide: "token2022-not-spl" },
  "T22-014": { fix: "Thaw frozen default-state accounts after creation.", guide: "vault-extensions" },
  "T22-015": { fix: "Use amount_to_ui_amount for interest-bearing mint pricing.", guide: "transfer-fees" },
  "T22-016": { fix: "Require mint.close_authority is None before accepting deposits.", guide: "vault-extensions" },
  "T22-017": { fix: "Re-derive and verify extra-account owners/PDAs in the hook.", guide: "transfer-hook-checklist" },
  "T22-018": { fix: "Validate GroupPointer and MemberPointer bidirectionally.", guide: "extension-pointers" },
  "T22-019": { fix: "Require metadata pointer authority matches the mint.", guide: "extension-pointers" },
  "T22-020": { fix: "Apply ScaledUiAmount multiplier before pricing on raw amount.", guide: "extension-pointers" },
  "T22-021": { fix: "Read transfer fee for the current epoch (newer/older fee).", guide: "transfer-fees" },
  "T22-022": { fix: "Detect NonTransferable extension before transferring.", guide: "token2022-not-spl" },
  "T22-023": { fix: "Check Pausable is_paused before issuing transfers.", guide: "extension-pointers" },
  "T22-024": { fix: "Verify hook program upgrade authority before trusting hook id.", guide: "transfer-hook-checklist" },
  "T22-025": { fix: "Reload mint account after CPI before using mint_authority.", guide: "extension-pointers" },
  "T22-026": { fix: "Check AccountState / thaw before transferring tokens.", guide: "vault-extensions" },
};
